### ISSUE TITLE
Old addon versions are downloading

### ISSUE THREAD

**Issue by olloff** [Akselmo/ESOLinuxAddonManager#20]
Steps:
1. Download the file from https://cdn.esoui.com/downloads/file3282/
2. Download the file from https://cdn.esoui.com/downloads/file3282/1
3. Compare addon versions

Result: 
1. https://cdn.esoui.com/downloads/file3282/ => 2.5.1
2. https://cdn.esoui.com/downloads/file3282/1 => 2.6.2

**Comment by Akselmo** [comment]
Fixed in: https://github.com/Akselmo/ESOLinuxAddonManager/commit/9125c0d0965d76ceeddaa271a423e86a5a00c256

**Comment by olloff** [comment]
Thank you so much :+1:
